idp:
  name: IDP
  description: IDP - Production
  realm: prod
  dbtype: mssql
  dbconfig:
    server: sqldb-server-hostname
    database: IDP_db
    user: IDP_user
    password: password***

# idd:
#   name: IDD
#   description: IDD - Development
#   realm: test
#   dbtype: mssql
#   dbconfig:
#     server: sqldb-server-hostname
#     database: IDD_db
#     user: IDD_user
#     password: password***
